### ISSUE TITLE
Logs to debug remote write issues

### ISSUE THREAD

**Issue by ratovarius** [dpattmann/prometheus-timestream-adapter#82]
I created an aws timestream db named `prometheus-database` and a table named `prometheus-table`.
I modified the region on main.go to match my region.
Build and pushed the docker image to ecr.

I have prometheus running in a kubernetes cluster. I patched the prometheus container,
```
  ...
  containers: # container for your adapter
    - name: timestream-adapter
      image: xxx.dkr.ecr.us-east-1.amazonaws.com/timestream-adapter
  remote_write:
    url: "http://localhost:9201/write"
```

The pod is named `prometheus-prometheus-0`. I see the timescream-adapter running on the pod,
`k describe pod prometheus-prometheus-0 -n prometheus`

```
Name:         prometheus-prometheus-0
...
Containers:
...
  timestream-adapter:
    Container ID:   docker://a7ec874984a973bf588acb8810fc9bc20357a8014ba0aa9ca0d3eeae7ca50296
    Image:          285651481985.dkr.ecr.us-east-1.amazonaws.com/timestream-adapter
    Image ID:       docker-pullable://285651481985.dkr.ecr.us-east-1.amazonaws.com/timestream-adapter@sha256:4f73e6a3b127685924056497b6650f76043353a5637a1883dfcfea9d27a9b2cc
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Thu, 27 Jan 2022 14:14:36 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-zm6mb (ro)
...

```

I can't see any data in the database. Is there a way to print some logs to checl for some connectivity issues?

`k logs prometheus-prometheus-0 -n prometheus -c timestream-adapter`
does not print anything

**Comment by ratovarius** [comment]
I solved this by correctly patching prometheus with,
```
  ...
  containers: # container for your adapter
    - name: timestream-adapter
      image: xxx.dkr.ecr.us-east-1.amazonaws.com/timestream-adapter
  remoteWrite:
    - url: "http://localhost:9201/write"
```
